import type { FileObject, FileStatus } from "@ice24/contracts";

export const fileStatusLabels: Record<FileStatus, string> = {
  pending: "Pendiente de carga",
  uploaded: "Recibido",
  processing: "En verificación (cuarentena)",
  available: "Disponible",
  rejected: "Rechazado",
  quarantined: "En cuarentena",
  deleted_temporary: "Cancelado o expirado",
};

export type Verdict = "approved" | "rejected" | "quarantine" | "pending" | "closed";

/** Antimalware review result of a status (F5-09: nothing is usable before validation). */
export function verdictOf(status: FileStatus): {
  verdict: Verdict;
  label: string;
  tone: "ok" | "danger" | "warning" | "neutral" | "info";
  explanation: string;
} {
  switch (status) {
    case "available":
      return {
        verdict: "approved",
        label: "Aprobado",
        tone: "ok",
        explanation: "Pasó la verificación de integridad y antimalware; se puede descargar.",
      };
    case "rejected":
      return {
        verdict: "rejected",
        label: "Rechazado",
        tone: "danger",
        explanation:
          "No pasó la verificación (malware, integridad o tipo real distinto) y sus bytes se eliminaron. Sube una copia limpia.",
      };
    case "processing":
    case "uploaded":
      return {
        verdict: "quarantine",
        label: "En cuarentena",
        tone: "warning",
        explanation:
          "El archivo espera la verificación antimalware. No se puede descargar hasta que se apruebe.",
      };
    case "quarantined":
      return {
        verdict: "quarantine",
        label: "En cuarentena",
        tone: "warning",
        explanation:
          "La verificación no pudo completarse y el archivo sigue aislado. Soporte puede reprocesarlo desde el Centro de trabajos.",
      };
    case "pending":
      return {
        verdict: "pending",
        label: "Pendiente",
        tone: "info",
        explanation: "La carga se autorizó pero aún no se confirma.",
      };
    case "deleted_temporary":
      return {
        verdict: "closed",
        label: "Sin archivo",
        tone: "neutral",
        explanation:
          "La carga se canceló o su autorización expiró. Súbelo de nuevo si lo necesitas.",
      };
  }
}

export type VariantName = "original" | "optimized" | "public";

/**
 * Downloadable versions of FIL-004. Only the private original exists today: derivatives
 * (optimized, public) are generated by later modules and are never offered before they exist.
 */
export function versionsOf(status: FileStatus): {
  name: VariantName;
  label: string;
  available: boolean;
  note: string;
}[] {
  const approved = status === "available";
  return [
    {
      name: "original",
      label: "Original privado",
      available: approved,
      note: approved
        ? "Descarga con enlace temporal de pocos minutos; cada descarga queda auditada."
        : "Disponible cuando la verificación lo apruebe.",
    },
    {
      name: "optimized",
      label: "Versión optimizada",
      available: false,
      note: "No generada para este archivo.",
    },
    {
      name: "public",
      label: "Versión pública",
      available: false,
      note: "No publicada: los archivos privados no tienen versión pública.",
    },
  ];
}

const MiB = 1_048_576;
export const formatSize = (bytes: number) =>
  bytes >= MiB ? `${(bytes / MiB).toFixed(1)} MB` : `${Math.max(1, Math.round(bytes / 1024))} KB`;

const RESOURCE_LABELS: Record<FileObject["relatedResource"]["type"], string> = {
  account: "Cuenta",
  branch: "Sucursal",
  machine: "Máquina",
};
export const resourceLabel = (resource: FileObject["relatedResource"]) =>
  `${RESOURCE_LABELS[resource.type]} ${resource.id.slice(0, 8)}`;
