import type { ApiResponseSchemaHost } from "@nestjs/swagger";
import { subscriptionStatusSchema } from "@ice24/contracts";

export const subscriptionOpenApiSchema: ApiResponseSchemaHost["schema"] = {
  type: "object",
  additionalProperties: false,
  required: [
    "id",
    "accountId",
    "provider",
    "providerCustomerId",
    "providerSubscriptionId",
    "planCode",
    "price",
    "status",
    "currentPeriodStart",
    "currentPeriodEnd",
    "cancelAtPeriodEnd",
    "isDemo",
    "demoExpiresAt",
    "version",
    "createdAt",
    "updatedAt",
    "accessMode",
    "audit",
  ],
  properties: {
    audit: {
      type: "object",
      required: ["createdAt", "createdBy", "updatedAt", "updatedBy", "version"],
      properties: {
        createdAt: { type: "string", format: "date-time" },
        createdBy: { type: "string", format: "uuid" },
        updatedAt: { type: "string", format: "date-time" },
        updatedBy: { type: "string", format: "uuid" },
        version: { type: "integer", minimum: 1 },
      },
    },
    id: { type: "string", format: "uuid" },
    accountId: { type: "string", format: "uuid" },
    provider: { type: "string", enum: ["stripe"] },
    providerCustomerId: { type: "string", nullable: true, maxLength: 255 },
    providerSubscriptionId: { type: "string", nullable: true, maxLength: 255 },
    planCode: { type: "string", maxLength: 80 },
    price: {
      type: "object",
      required: ["amountMinor", "currency"],
      properties: {
        amountMinor: { type: "integer", minimum: 0, maximum: Number.MAX_SAFE_INTEGER },
        currency: { type: "string", enum: ["MXN"] },
      },
    },
    status: { type: "string", enum: subscriptionStatusSchema.options },
    currentPeriodStart: { type: "string", format: "date-time", nullable: true },
    currentPeriodEnd: { type: "string", format: "date-time", nullable: true },
    cancelAtPeriodEnd: { type: "boolean" },
    isDemo: { type: "boolean" },
    demoExpiresAt: { type: "string", format: "date-time", nullable: true },
    version: { type: "integer", minimum: 1 },
    createdAt: { type: "string", format: "date-time" },
    updatedAt: { type: "string", format: "date-time" },
    accessMode: { type: "string", enum: ["ACTIVE", "READ_ONLY", "SUSPENDED"] },
  },
};
